#!/usr/bin/env python3
"""
peakatail_topn_rank.py -- rank PeakATail PAS by total UMI depth and emit
matched-N top-N point BEDs for scoring with scripts/benchmark_tools/score_tool.py.

WHY THIS SCRIPT EXISTS
    The top-N arms quoted in manuscript/09_headtohead_results.md ("ranking its
    277k calls by total UMI count and scoring the top 22k / 36k / 106k gives
    precision 0.119 / 0.120 / 0.118") were produced by an uncommitted one-off
    that paired
        zip(pas.bed names, row sums of run/annotated_matrix.mtx)
    pas.bed is COORDINATE-sorted; the matrix rows are pas_id-ordered, as
    recorded in 05_annotated_matrix/<strategy>/annotated_pas_ids.tsv.  The two
    are permutations of the same id set, so nothing crashed and no length
    assert fired -- but 99.8% of PAS were ranked on another PAS's depth.
    This is item 0g of manuscript/10_caller_fix_plan.md; the same defect was
    fixed in benchmark_headtohead.depth_map().

    --emulate-bug reproduces the old, wrong pairing bit-for-bit so the shipped
    numbers stay auditable.

USAGE
    python3 scripts/manuscript_figures/peakatail_topn_rank.py \
        --run  results/benchmark_tools/pbmc_10k_v3/peakatail/run \
        --bed  results/benchmark_tools/pbmc_10k_v3/peakatail/pas.bed \
        --outdir results/benchmark_tools/pbmc_10k_v3/peakatail/topN_rekeyed \
        --n 22000 36000 106000

TIE-BREAK: descending depth, then ascending int(pas_id) -- deterministic and
    independent of input order, so the selection is reproducible.
"""
import argparse
from pathlib import Path


def mtx_rowsums(path):
    """Row sums of a MatrixMarket coordinate file (comment lines start with %)."""
    sums = None
    with open(path) as fh:
        for line in fh:
            if line.startswith("%"):
                continue
            f = line.split()
            if sums is None:                       # first non-comment line = dims
                sums = [0] * int(f[0])
                continue
            sums[int(f[0]) - 1] += int(f[2])
    return sums


def row_ids(run):
    cands = sorted((run / "05_annotated_matrix").glob("*/annotated_pas_ids.tsv"))
    assert len(cands) == 1, f"expected one annotated_pas_ids.tsv under {run}: {cands}"
    lines = cands[0].read_text().splitlines()
    assert lines[0].strip() == "pas_id", lines[:1]
    return [l.strip() for l in lines[1:] if l.strip()]


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--run", type=Path, required=True, help="PeakATail run/ directory")
    ap.add_argument("--bed", type=Path, required=True,
                    help="point BED6 to rank (pas.bed); name column = pas_id")
    ap.add_argument("--outdir", type=Path, required=True)
    ap.add_argument("--n", type=int, nargs="+", required=True)
    ap.add_argument("--emulate-bug", action="store_true",
                    help="reproduce the pre-2026-08-19 mis-pairing (audit only)")
    a = ap.parse_args()

    rows = [l.split("\t") for l in a.bed.read_text().splitlines() if not l.startswith("#")]
    names = [r[3] for r in rows]
    sums = mtx_rowsums(a.run / "annotated_matrix.mtx")
    ids = row_ids(a.run)
    assert len(ids) == len(sums), (len(ids), len(sums))
    assert set(names) == set(ids), f"{len(set(names) ^ set(ids))} ids differ"

    if a.emulate_bug:
        depth = dict(zip(names, sums))             # WRONG: BED order vs row order
        tag = "bug-emulation (pas.bed line order zipped onto matrix rows)"
    else:
        depth = dict(zip(ids, sums))               # keyed on annotated_pas_ids.tsv
        tag = "keyed on 05_annotated_matrix/*/annotated_pas_ids.tsv"

    order = sorted(names, key=lambda p: (-depth[p], int(p)))
    a.outdir.mkdir(parents=True, exist_ok=True)
    for n in a.n:
        keep = set(order[:n])
        out = a.outdir / f"pas_top{n}.bed"
        with open(out, "w") as fh:
            fh.write(f"# PeakATail PAS ranked by total UMI count (row sums of "
                     f"{a.run.name}/annotated_matrix.mtx), {tag};\n"
                     f"# top {n} retained.  Generated by "
                     f"scripts/manuscript_figures/peakatail_topn_rank.py\n")
            for r in rows:                          # keep input (coordinate) order
                if r[3] in keep:
                    fh.write("\t".join([r[0], r[1], r[2], r[3],
                                        str(depth[r[3]]), r[5]]) + "\n")
        print(f"wrote {out}  n={len(keep)}  "
              f"depth range {depth[order[n-1]]}..{depth[order[0]]}")


if __name__ == "__main__":
    main()
